// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {network} from '../models';

export function CheckCom0ComInstalled():Promise<boolean>;

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAppConfig():Promise<main.AppConfig>;

export function GetCurrentUsername():Promise<string>;

export function GetDevices():Promise<Array<network.Device>>;

export function GetLogPath():Promise<string>;

export function GetStatus():Promise<main.ConnectionStatus>;

export function GetVersion():Promise<string>;

export function IsLoggedIn():Promise<boolean>;

export function LoadConfig():Promise<main.AppConfig>;

export function Login(arg1:string,arg2:string):Promise<network.User>;

export function Logout():Promise<void>;

export function SaveConfig(arg1:string,arg2:boolean):Promise<void>;
